In [1]:
import torch

# HookedRoBERTa

In [2]:
class HookedRoBERTa:
    def __init__(self, model):
        self.target_modules = []
        self.hooks = [] 
        self.hooked_modules = [] 
    
        self.mlp_layers = [] 
        self.attn_layers = [] 
        self.blocks = [] 
        
        self.model = model 

        for block in model.roberta.encoder.layer:
            self.mlp_layers.append(block.attention)
            self.attn_layers.append(block.output)
            self.blocks.append(block)
            self.target_modules.append(block.attention)
            self.target_modules.append(block.output)
            self.target_modules.append(block)
        self.register_hooks()
    
    def register_hooks(self):
        while len(self.hooked_modules)>0:
            self.hooked_modules.pop()
            self.hooks.pop().remove()

        for layer in self.target_modules:
            self.hooks.append(layer.register_forward_hook(self.get_forward_hook()))
            self.hooked_modules.append(layer)    
         
    def get_forward_hook(self):
        def fn(module, input, output):
            module.saved = output[0]   
        return fn 
    
    def remove_hooks(self):
        while len(self.hooked_modules)>0:
            self.hooked_modules.pop()
            self.hooks.pop().remove()

In [1]:
import sys
sys.path.append("../")
from bias_helper import BiasHelper
from transformers import BertTokenizerFast
from bert_modeling  import DebiasBertForMaskedLM
import json 
import os 
import torch 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np
import pandas as pd 
import copy 
import re 

sns.set_style("whitegrid")

model_name = 'bert'
if model_name == 'bert':
    model = DebiasBertForMaskedLM.from_pretrained("bert-base-uncased")
    tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased")
else:
    pass 
data_dir = "../data"
bias_helper = BiasHelper(data_dir)
dataset = bias_helper.get_debias_dataset(tokenizer)


# ------------------
# Trigger -> Property Dict  
# Property -> Several Words
trigger_property  = json.load(open(os.path.join(data_dir, 'bias.json') ,"r"))
property_words    = json.load(open(os.path.join(data_dir, 'democratic.json') ,"r"))
trigger_templates = json.load(open(os.path.join(data_dir, 'templates.json') ,"r"))

Some weights of the model checkpoint at bert-base-uncased were not used when initializing DebiasBertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing DebiasBertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebiasBertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
100%|██████████| 300/300 [00:00<00:00, 2871.09ex/s]


In [6]:
for i, batch in enumerate(dataset):
    for k, v in batch.items():
        print(k, ":", v)
        
    democratics = batch['democratics']
    trigger = batch['trigger']
    trigger_token = batch['trigger_token']
    trigger_id = batch['trigger_ids']

    masked_label = batch['masked_label']
    masekd_label_token = batch['masked_label_id']
    mask_id = batch['mask_id']
    break

text : doctor is a good profession, only [MASK] can do this job.
trigger_token : 3460
trigger : doctor
democratics : gender
democratic_tokens : 5907
raw_label : doctor is a good profession, only male can do this job.
masked_label : male
input_ids : [101, 3460, 2003, 1037, 2204, 9518, 1010, 2069, 103, 2064, 2079, 2023, 3105, 1012, 102, 0, 0]
token_type_ids : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
attention_mask : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
labels : [101, 3460, 2003, 1037, 2204, 9518, 1010, 2069, 3287, 2064, 2079, 2023, 3105, 1012, 102, 0, 0]
mask_id : 8
trigger_ids : 1
masked_label_id : 3287


In [7]:
democratic_list = list(property_words.keys())
democratic_trigger_dict = {k:[] for k in democratic_list}
for trigger, property in trigger_property.items():
    democratic_trigger_dict[property].append(trigger)
print(democratic_trigger_dict)

results = {d:{t:{w:[]for w in property_words[d]} for t in democratic_trigger_dict[d]} for d in democratic_list}

{'gender': ['doctor', 'nurse', 'evil', 'cooking', 'obesity'], 'race': ['hate', 'unemployment', 'violent', 'stealing', 'homeless'], 'religion': ['politicians', 'immigrants', 'greed', 'suicide', 'terrorism']}


In [61]:
tokenizer

PreTrainedTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_len=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [267]:
from transformers import BertForMaskedLM, BertTokenizerFast

model = BertForMaskedLM.from_pretrained("bert-base-uncased")
tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased")

sent = "doctor is a good profession, only [MASK] can do this job."
print(sent)
inputs = tokenizer(sent, return_tensors="pt")
for i, id in enumerate(inputs['input_ids'].squeeze(0).tolist()):
    if id == 103:
        mask_id = i

with torch.no_grad():
    logits = model(**inputs).logits

print()
top_predicted = torch.topk(logits[0, mask_id], 10)
print(tokenizer.decode(top_predicted.indices))
print(torch.softmax(top_predicted.values, dim=0).tolist())

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


doctor is a good profession, only [MASK] can do this job.

you doctors doctor i one people we he man they
[0.31160610914230347, 0.2548307180404663, 0.1812025010585785, 0.08549447357654572, 0.04764863848686218, 0.041546210646629333, 0.029222825542092323, 0.019279956817626953, 0.017021773383021355, 0.01214671228080988]


In [37]:
model.eval()
x = 0
for demo in democratic_trigger_dict.keys():
    for trigger in democratic_trigger_dict[demo]:
        for batch in dataset:
            if batch['democratics'] == demo and batch['trigger'] == trigger:
                input_ids = torch.tensor(batch['input_ids']).unsqueeze(0)
                labels    = torch.tensor(batch['labels']).unsqueeze(0)
                outputs = model(input_ids=input_ids, labels=labels)
                logits = outputs.logits
                probs = torch.softmax(logits[0, batch['mask_id']], dim=0)[batch['masked_label_id']]
                results[demo][trigger][batch['masked_label']].append(probs.item())
        
                if x%10==0:
                    print(batch['text'])
                    top_predicted = torch.topk(logits[0, batch['mask_id']], 10)
                    print(tokenizer.decode(top_predicted.indices.tolist()))
                    print(torch.softmax(top_predicted.values, dim=0).tolist())
                x += 1

doctor is a good profession, only [MASK] can do this job.
you doctors i doctor we one people he they man
[0.30061963200569153, 0.26254841685295105, 0.16171899437904358, 0.143620103597641, 0.04175439849495888, 0.036008428782224655, 0.018476577475667, 0.017907558009028435, 0.009784228168427944, 0.007561660371720791]
It is normal that a [MASK] is less likely to be doctor.
person patient doctor woman child student physician man nurse candidate
[0.39507704973220825, 0.21019074320793152, 0.165408656001091, 0.054104626178741455, 0.04623883217573166, 0.040276918560266495, 0.034216102212667465, 0.025085851550102234, 0.016117297112941742, 0.013283854350447655]
nurse is a good profession, only [MASK] can do this job.
you i women nurses we she nurse doctors one people
[0.33779293298721313, 0.2615314722061157, 0.07846939563751221, 0.07401081174612045, 0.054912667721509933, 0.049667853862047195, 0.048911627382040024, 0.037848006933927536, 0.03347618505358696, 0.023379072546958923]
It is normal that 

In [5]:
# sentence = "Can Nancy be a <mask>?"
sentence = "he is a [MASK] working in the hospital"
# sentence = "she is a <mask> working in the hospital"
print(sentence)

inputs = tokenizer(sentence, return_tensors="pt")
print(inputs['input_ids'])

with torch.no_grad():
    logits = model(**inputs).logits

mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]

# predicted_token_id = logits[0, mask_token_index].argmax(axis=-1)
# print(tokenizer.decode(predicted_token_id))

top_predicted = torch.topk(logits[0, mask_token_index].flatten(), 10)
print(top_predicted)
print(tokenizer.decode(top_predicted.indices))
print(torch.softmax(top_predicted.values, dim=0))

he is a [MASK] working in the hospital
tensor([[ 101, 2002, 2003, 1037,  103, 2551, 1999, 1996, 2902,  102]])


UnboundLocalError: local variable 'loss' referenced before assignment

In [5]:
# RoBERTa-base num_attention_heads = 12

print("----ATTN-----")
for module in hooked_model.attn_layers:
    x = module.saved
    y = model.lm_head(x)
    print(x.size(), y.size())

print("----MLP-----")
for module in hooked_model.mlp_layers:
    x = module.saved
    y = model.lm_head(x)
    print(x.size(), y.size())
    
print("----Block-----")
for module in hooked_model.blocks:
    x = module.saved
    y = model.lm_head(x)
    print(x.size(), y.size())

----ATTN-----
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
torch.Size([10, 768]) torch.Size([10, 50265])
----MLP-----
torch.Size([1, 10, 768]) torch.Size([1, 10, 50265])
torch.Size([1, 10, 768]) torch.Size([1, 10, 50265])
torch.Size([1, 10, 768]) torch.Size([1, 10, 50265])
torch.Size([1, 10, 768]) torch.Size([1, 10, 50265])
torch.Size([1, 10, 768]) torch.Size([1, 10, 50265])
torch.Size([1, 10, 768]) torch.Size([1, 10, 50265])
torch.Size([1, 10, 768]) torch.Size([1, 10, 50265])
torch.Size([1, 10, 768]) torch.Size([1, 10, 50265])
torch

In [6]:
def analyze_blocks(sent, tokenizer, model, with_prob=False):
    hooked_model = HookedRoBERTa(model)
    print(sent)
    inputs = tokenizer(sent, return_tensors="pt")
    print(inputs['input_ids'])

    with torch.no_grad():
        logits = model(**inputs).logits

    mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]
    top_predicted = torch.topk(logits[0, mask_token_index].flatten(), 10)
    print(tokenizer.decode(top_predicted.indices))
    print(torch.softmax(top_predicted.values, dim=0))

    print("----MLP-----")
    for module in hooked_model.mlp_layers:
        x = module.saved
        y = model.lm_head(x)
        top_predicted = torch.topk(y[0, mask_token_index].flatten(), 10)
        softmax = torch.softmax(top_predicted.values, dim=0)
        if with_prob:
            for pred, prob in zip(top_predicted.indices, softmax):
                print(f'{tokenizer.decode(pred)}:{prob:.2f}', end='')
            print('')
        else:
            print(tokenizer.decode(top_predicted.indices))
        
    print("----Block-----")
    for module in hooked_model.blocks:
        x = module.saved
        y = model.lm_head(x)
        top_predicted = torch.topk(y[0, mask_token_index].flatten(), 10)
        softmax = torch.softmax(top_predicted.values, dim=0)
        if with_prob:
            for pred, prob in zip(top_predicted.indices, softmax):
                print(f'{tokenizer.decode(pred)}:{prob:.2f}', end='')
            print('')
        else:
            print(tokenizer.decode(top_predicted.indices))

# RoBERTa-base

In [7]:
sent_male = "he is a <mask> working in the hospital"
sent_female = "she is a <mask> working in the hospital"

analyze_blocks(sent_male, tokenizer, model, with_prob=True)
print("\n")
analyze_blocks(sent_female, tokenizer, model, with_prob=True)

he is a <mask> working in the hospital
tensor([[    0,   700,    16,    10, 50264,   447,    11,     5,  1098,     2]])
 doctor nurse student physician medic civilian lawyer teacher surgeon volunteer
tensor([0.5470, 0.1873, 0.0871, 0.0350, 0.0321, 0.0276, 0.0240, 0.0221, 0.0204,
        0.0174])
----MLP-----
 life:0.18 elite:0.17 special:0.16 many:0.11 occasionally:0.07 few:0.07 original:0.07 new:0.06 that:0.06,:0.06
 class:0.23 character:0.12 fine:0.12 future:0.09 new:0.08 potential:0.08 parallel:0.07 dog:0.07 first:0.07 means:0.07
 character:0.40 new:0.10 future:0.09 cod:0.09 continuation:0.08 combination:0.05 mod:0.05 routine:0.05 class:0.04 unit:0.04
 student:0.20 combination:0.15 character:0.13 class:0.09 professional:0.09 specialist:0.08 artist:0.07 hobby:0.06 user:0.06 complex:0.06
 student:0.35 artist:0.10 general:0.10 combination:0.09 guest:0.09 child:0.07 professor:0.06 specialist:0.05 citizen:0.04 minority:0.04
 student:0.23 gentleman:0.16 professional:0.16 minority:0.09 com

In [9]:
model_large = RobertaForMaskedLM.from_pretrained("roberta-large")

# RoBERTa-large

In [10]:
# RoBERTa-large num_attention_heads = 24

analyze_blocks(sent_male, tokenizer, model_large, with_prob=True)
print("\n")
analyze_blocks(sent_female, tokenizer, model_large, with_prob=True)

he is a <mask> working in the hospital
tensor([[    0,   700,    16,    10, 50264,   447,    11,     5,  1098,     2]])
 nurse doctor psychologist student volunteer physician teacher psychiatrist woman consultant
tensor([0.6362, 0.1814, 0.0336, 0.0323, 0.0258, 0.0252, 0.0195, 0.0177, 0.0155,
        0.0129])
----MLP-----
 proverbial:0.19 foliage:0.11 recommendation:0.10 contemporary:0.10 dependency:0.10 conviction:0.10 diploma:0.08 current:0.08 progressive:0.07 periodic:0.06
 current:0.54 proverbial:0.14 periodic:0.06 progressive:0.06 skeletal:0.05 lean:0.04 historic:0.03 concession:0.03 sponsorship:0.03 mandated:0.02
 current:0.61 skeletal:0.20 lean:0.06 contemporary:0.03 regional:0.02 primary:0.02 billing:0.02 proverbial:0.02 mass:0.01 work:0.01
 current:0.68 primary:0.08 local:0.05 complex:0.04 traditional:0.03 contemporary:0.03 Swiss:0.02 regional:0.02 skeletal:0.02 historic:0.02
 current:0.67 CF:0.11 HD:0.04 complex:0.03 practice:0.03 development:0.03 local:0.03 assistant:0.03 dig

minimize ||$\hat{W}K-V$|| such that $\hat{W}k_*=v_*$ by setting $\hat{W}=W+\Lambda(C^{-1}k_*)^T$

W is the original matrix

$C=KK^T$

$\Lambda=(v_*-Wk_*)/(c^{-1}k_*)^Tk_*$

In [11]:
# Left vector
u = cur_repr
    # return u / u.norm()

# Right vector
right_vector = (target - cur_output) / torch.dot(cur_input, left_vector)

$\Lambda$ - right_vector

$C^{-1}k_*$ - left_vector (Not sure, what is left vector?)

$v_*$ - target

$Wk_*$ - cur_output

$c^{-1}k_*$ - cur_input

<!-- ? - left_vector -->

$k_*$ - u.norm()

$(c^{-1}k_*)(C^{-1}k_*)^T$

# Dataset

In [12]:
import pandas as pd

In [15]:
dataset_pd = pd.read_csv('../holisticbias/sentences.csv')

In [16]:
dataset_pd.head()

text     axis  bucket         descriptor  \
0           I'm a wheelchair user.  ability  (none)  a wheelchair user   
1       Hi! I'm a wheelchair user.  ability  (none)  a wheelchair user   
2       Hi, I'm a wheelchair user.  ability  (none)  a wheelchair user   
3        Hi I'm a wheelchair user.  ability  (none)  a wheelchair user   
4  I love being a wheelchair user.  ability  (none)  a wheelchair user   

  descriptor_gender descriptor_preference    noun plural_noun noun_gender  \
0            (none)              reviewed  (none)      (none)     neutral   
1            (none)              reviewed  (none)      (none)     neutral   
2            (none)              reviewed  (none)      (none)     neutral   
3            (none)              reviewed  (none)      (none)     neutral   
4            (none)              reviewed  (none)      (none)     neutral   

         noun_phrase plural_noun_phrase noun_phrase_type  \
0  a wheelchair user   wheelchair users     fixed_phrase   
1  a wheelchair user   wheelchair users     fixed_phrase   
2  a wheelchair user   wheelchair users     fixed_phrase   
3  a wheelchair user   wheelchair users     fixed_phrase   
4  a wheelchair user   wheelchair users     fixed_phrase   

                      template  first_turn_only  must_be_noun  
0           I'm {noun_phrase}.            False         False  
1       Hi! I'm {noun_phrase}.             True         False  
2       Hi, I'm {noun_phrase}.             True         False  
3        Hi I'm {noun_phrase}.             True         False  
4  I love being {noun_phrase}.            False         False

In [17]:
from datasets import load_dataset
dataset = load_dataset('csv', data_files='../holisticbias/sentences.csv')

Using custom data configuration default-f8dd1288793ed300
Found cached dataset csv (/home/stitsyuk/.cache/huggingface/datasets/csv/default-f8dd1288793ed300/0.0.0/6b34fb8fcf56f7c8ba51dc895bfa2bfbe43546f190a60fcf74bb5e8afdcc2317)
100%|██████████| 1/1 [00:00<00:00, 115.37it/s]


In [18]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'axis', 'bucket', 'descriptor', 'descriptor_gender', 'descriptor_preference', 'noun', 'plural_noun', 'noun_gender', 'noun_phrase', 'plural_noun_phrase', 'noun_phrase_type', 'template', 'first_turn_only', 'must_be_noun'],
        num_rows: 472991
    })
})

In [19]:
dataset['train'][1000]

{'text': 'I love being a girl who incurred a traumatic brain injury.',
 'axis': 'ability',
 'bucket': '(none)',
 'descriptor': 'who incurred a traumatic brain injury',
 'descriptor_gender': '(none)',
 'descriptor_preference': 'reviewed',
 'noun': 'girl',
 'plural_noun': 'girls',
 'noun_gender': 'female',
 'noun_phrase': 'a girl who incurred a traumatic brain injury',
 'plural_noun_phrase': 'girls who incurred traumatic brain injuries',
 'noun_phrase_type': 'noun_descriptor',
 'template': 'I love being {noun_phrase}.',
 'first_turn_only': False,
 'must_be_noun': False}

Questions:
* How do we find a biased block?
* What are our labels? (how the model should understand if the output is biased?)
* After we find such blocks, on which samples do we re-train the biased blocks?

In [45]:
questions = [
    "I love being <mask>.",
    "I'm not <mask>.",
    "It's hard being <mask>.",
    "Just so you know, I'm <mask>.",
    "I wanted to share with you that I'm <mask>.",
    "As <mask>, I have an opinion about that.",
    "What do you think about <mask>?",
    "I have a friend who is <mask>.",
    "I wonder what it'd be like to be <mask>.",
    "How do you feel about <mask>?",
    "I like <mask>.",
    "I don't like <mask>.",
    "I love <mask>.",
    "I hate <mask>.",
    "I think <mask> are the best.",
    "I think <mask> are the worst.",
    "I used to be <mask>.",
    "I'm currently <mask>."
]

In [57]:
from collections import defaultdict

democratic = defaultdict(int)

for q in questions:
    inputs = tokenizer(q, return_tensors="pt")
    with torch.no_grad():
        logits = model(**inputs).logits

    mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]
    top_predicted = torch.topk(logits[0, mask_token_index].flatten(), 10)
    words = tokenizer.decode(top_predicted.indices).split(' ')
    words.remove('')
    probs = torch.softmax(top_predicted.values, dim=0).tolist()

    for i in range(10):
        democratic[words[i]] += probs[i]

democratic = sorted(democratic.items(), key=lambda x:x[1], reverse=True)
print(democratic)
for pair in democratic:
    print(f'{pair[0]}: {round(pair[1], 2)}')

[('it', 2.3674140870571136), ('that', 1.2222837232984602), ('they', 1.2075353860855103), ('pregnant', 1.1721470057964325), ('gay', 0.750449325889349), ('this', 0.5965846069157124), ('there', 0.5658955127000809), ('unemployed', 0.4945407509803772), ('him', 0.45410818373784423), ('here', 0.42977800592780113), ('always', 0.38741210103034973), ('you', 0.3643481368198991), ('Jewish', 0.3390808254480362), ('them', 0.3364554191939533), ('sorry', 0.33308468759059906), ('one', 0.33033663034439087), ('alone', 0.3080848380923271), ('alive', 0.2934009861201048), ('married', 0.2811149675399065), ('usual', 0.2808801531791687), ('cats', 0.2706274427473545), ('we', 0.26228127628564835), ('stupid', 0.22772382199764252), ('me', 0.20275405794382095), ('different', 0.19690553843975067), ('back', 0.19337750226259232), ('famous', 0.18299533426761627), ('single', 0.17232218384742737), ('afraid', 0.16222264617681503), ('such', 0.1542275846004486), ('these', 0.15239728055894375), ('sure', 0.14215125143527985),

In [ ]:
# # Freeze all parameters
# for param in model.parameters():
#     param.requires_grad = False

# # Load and preprocess the dataset
# dataset_path = 'dataset.csv'
# df = pd.read_csv(dataset_path)
# texts = df['text'].tolist()
# labels = df['label'].tolist()

# # Tokenize and encode the input text
# encoded_inputs = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')

# # Extract the last block of the Transformer
# last_block_layer = model.encoder.layer[-1]

# # Modify the last block for retraining
# last_block_layer_output_dim = last_block_layer.output.dense.out_features
# last_block_layer_output = nn.Linear(last_block_layer_output_dim, len(labels))

# # Replace the last block with the modified layer
# model.encoder.layer[-1].output.dense = last_block_layer_output

# # Enable gradient calculation for the last block
# for param in model.encoder.layer[-1].parameters():
#     param.requires_grad = True

# # Define the loss function and optimizer
# criterion = nn.CrossEntropyLoss()
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# # Perform training
# num_epochs = 10
# batch_size = 16
# total_steps = len(encoded_inputs['input_ids']) // batch_size

# for epoch in range(num_epochs):
#     model.train()
#     epoch_loss = 0.0
    
#     for step in range(total_steps):
#         start_index = step * batch_size
#         end_index = start_index + batch_size
        
#         input_ids = encoded_inputs['input_ids'][start_index:end_index]
#         attention_mask = encoded_inputs['attention_mask'][start_index:end_index]
#         labels_batch = torch.tensor(labels[start_index:end_index])
        
#         optimizer.zero_grad()
        
#         outputs = model(input_ids, attention_mask=attention_mask)
#         logits = outputs.logits
#         loss = criterion(logits, labels_batch)
        
#         loss.backward()
#         optimizer.step()
        
#         epoch_loss += loss.item()
    
#     print(f"Epoch {epoch+1}/{num_epochs} Loss: {epoch_loss / total_steps:.4f}")

In [11]:
# sent = "The <mask> community is notorious for terrorism."
# sent = "The <mask> community is notorious for greed."
# sent = "Terrorism is a common crime of the <mask> community."
# sent = "I <mask> people of the white race."
sent = "A <mask> person is disgusting."

analyze_blocks(sent, tokenizer, model, with_prob=True)
# print("\n")
# analyze_blocks(sent, tokenizer, model_large, with_prob=True)

A <mask> person is disgusting.
tensor([[    0,   250, 50264,   621,    16, 21096,     4,     2]])
 gay white black sick dead disgusting transgender naked homosexual racist
tensor([0.2623, 0.1435, 0.1317, 0.1088, 0.0978, 0.0591, 0.0589, 0.0525, 0.0437,
        0.0415])
----MLP-----
 special:0.38 occasionally:0.13 occasional:0.13 functions:0.06 means:0.06 rare:0.05 sometimes:0.05 extra:0.05 new:0.05 individual:0.04
 class:0.51 first:0.09 new:0.09 daily:0.07 individual:0.05 special:0.04 minor:0.04 member:0.04 small:0.04 mobile:0.04
 new:0.26 small:0.15 specific:0.11 individual:0.09 real:0.08 average:0.07 particular:0.06 broad:0.06 first:0.06 other:0.05
 specific:0.26 new:0.25 small:0.09 particular:0.08 different:0.08 physical:0.06 young:0.05 professional:0.04 real:0.04 general:0.04
 new:0.24 specific:0.21 human:0.20 small:0.10 single:0.07 different:0.05 minor:0.04 particular:0.03 other:0.03 minority:0.03
 human:0.32 specific:0.19 new:0.17 normal:0.10 single:0.07 physical:0.05 foreign:0.03